## The makeCache and cacheSolve functions are used in tandem so that the intensive
## cpu time required to calculate the inverse of a matrix are only performed once
## and the inverse is held in cache memory and can be retrieved by calling the
## cacheSolve function again after the initial function call.
##
## Note that the code below assumes that the supplied matrix is invertable.


## The makeCacheMatrix function initializes supplied parameter x with
## a default value of a 1x1 NULL matrix. It returns a named list of 4 
## functions to be used for the setting and retrieval of matrix x and 
## its inverse. It also sets the potential cached object holding the 
## inverse of matrix x to NULL so that any previously calculated inverses
## are not erroneously carried forward. 
##
## Note that the $set function returned by makeCacheMatrix can be used 
## to reset the matrix x without again calling makeCacheMatrix. 
## For example:
## > m1 <- makeCacheMatrix(matrix(c(1:4), nrow = 2, ncol = 2))
## > cacheSolve(m1)
##      [,1] [,2]
## [1,]   -2  1.5
## [2,]    1 -0.5
## > m1$set(matrix(c(4:1), nrow = 2, ncol = 2))
## > cacheSolve(m1)
##      [,1] [,2]
## [1,] -0.5    1
## [2,]  1.5   -2

makeCacheMatrix <- function(x = matrix()) {
        i <- NULL
        set <- function(y) {
                x <<- y
                i <<- NULL
        }
        get <- function() x
        setinv <- function(inverse) i <<- inverse
        getinv <- function() i
        list(set = set, get = get,
             setinv = setinv,
             getinv = getinv)
}


## The cacheSolve function uses the list generated by the makeCacheMatrix 
## function to return the inverse of the matrix x defined by the most recent
## makeCacheMatrix call. If the inverse has not yet been solved it goes 
## through that potentially cpu-intensive computaton. However if the inverse
## has already been calculated by a previous call the cacheSolve function 
## avoids repeated that engthy processing and notes this by printing a message.

cacheSolve <- function(x, ...) {
        i <- x$getinv()
        if(!is.null(i)) {
                message("getting cached data")
                return(i)
        }
        data <- x$get()
        i <- solve(data, ...) # The solve function calculates the inverse
        x$setinv(i)
        i
}
